pipeline {
    agent {label 'aws-label'}

    stages {
        stage('Preparation') {
            steps {
                git 'https://github.com/ShehabEl-DeenAlalkamy/my-nodejs-ci-cd.git'
            }
        }
        stage('Build') {
            steps {
                sh 'docker build -t shehabeldeen/jenkins_iti:v1.0 .'
            }
        }
        stage('Artifact') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub', passwordVariable: 'pass', usernameVariable: 'username')]) {
                    sh 'docker login -u ${username} -p ${pass}'
                    sh 'docker push shehabeldeen/jenkins_iti:v1.0'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker run -d -p 3000:3000 shehabeldeen/jenkins_iti:v1.0'
            }
        }
    }
}
